### ISSUE TITLE
Pre-launch todo-list

### ISSUE THREAD

**Issue by jevakallio** [FormidableLabs/whackage#1]
Things to do before launch:

* [x] Blacklist .babelrc
* [x] Check that linked packages are also installed to the host project
* [x] Check that none of the linked packages are symlinks
* [x] Verify `rsync` availability across linux distros (or remove rsync)
* [x] Synchronise changes to npm dependencies (or document how to work-around)
* [x] `whack reset` to restore whacked deps
* [x] API documentation and better CLI messages
* [x] Preserve packager stdout colors and add some flair to `whackage` console output
